language: bash
sudo: required
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

before_install:
#ignore gitflow commits except version tag
- |
  if [[ "${TRAVIS_COMMIT_MESSAGE}" == "[gitflow]"* ]] && [[ "${TRAVIS_BRANCH}" != v[0-9]* ]] && [[ "${TRAVIS_BRANCH}" != development ]] && [[ "${TRAVIS_BRANCH}" != release-* ]]; then
    travis_terminate 0
  fi

before_script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
script:
- |
  if [[ "${TRAVIS_BRANCH}" == release-* ]]; then
    QUALIFIER=-frozen-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    QUALIFIER=-dev-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    QUALIFIER=""
  else
    QUALIFIER=-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  fi && ./.travis.scripts/mvn.sh build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'${QUALIFIER}
- "./.travis.scripts/mvn.sh -Dmaven.site.skip=true clean verify -B -e -V"
after_success:
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]] || [[ "${TRAVIS_BRANCH}" == release-* ]] || [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    ./.travis.scripts/mvn.sh sonar:sonar
  fi
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    ./.travis.scripts/mvn.sh -P github-site site  fi
deploy:
  provider: script
  script: "./.travis.scripts/mvn.sh -Dmaven.site.skip=true -P stage-devel-bintray deploy"
  skip_cleanup: true
  on:
    all_branches: true
branches:
  except: # web site and version tag
  - gh-pages
  - master
#  - /^v[0-9]/
env:
  matrix:
    secure: sbWo2B0CeC6d5yFdb3V44brLRLsDxIiCmnZ3t/7+gBlnb58SseyxBCOYDqhtE8YHnFIo+/4iSDJnsEiAO1fXqakDm7k/ZzI/oCnG8u8/qAjcpoNYapR8vun0s4+Ix3aMDjsp6GSl0dtqsOGLZOI3lnP1liHfb885mvL44OMACsD3P/JRYF5v4lvYakx1qmsJbl2fRbKvg/oaA5SXUR44om5cVujDxnHmJ7NP2tHqhlb3QNAI09Y/TfboIKID0ApACSQrEBEi0q1rZTg3XWJSanA7/Ke4UmVpgl5VdqW1D1w3GUgRWREG+nN1tQp6xe0Yy4729kIo6nUIiIQRZNLbXliI+n5WK6qB1mgAh4mS6jP/W/ZomqkbI0SkQLeLlP5txs+nvYSKpwCHQgeEyCyqKlFj/VsxerRNNzMGeIhp7CHR82yre+gKqRD1vAfBkO3pwqr8D+RlRRWRODY8BwfBoZeTpyGd3wD8ksbrXzuCxki5R6n2wajm9iW+TaJzz6QwszdKt0xJK5mb/OtkYTwCZmq46XBQU6LXXv5BjDAYYqWfKhVe7W74i6IiDFjqhrmCbBRITqyJ8l5rzkFcFnbUlucBNdmsKldgRTMTEQmpu8TtGB9b8C9Vy4r0MS1+8HCZAMNmVvuxHMS9/ZSMgn5CM9omS3SbiIzjPxNkbULvzTM=

