language: bash
sudo: required
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
- |
  if [[ "${TRAVIS_COMMIT_MESSAGE}" == "[gitflow]"* ]] && [[ "${TRAVIS_BRANCH}" != v[0-9]* ]] && [[ "${TRAVIS_BRANCH}" != development ]] && [[ "${TRAVIS_BRANCH}" != release-* ]]; then
    travis_terminate 0
  fi
before_script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
script:
- |
  if [[ "${TRAVIS_BRANCH}" == release-* ]]; then
    QUALIFIER=-frozen-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    QUALIFIER=-dev-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    QUALIFIER=""
  else
    QUALIFIER=-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  fi && ./.travis.scripts/mvn.sh build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'${QUALIFIER}
- "./.travis.scripts/mvn.sh -Dmaven.site.skip=true clean verify -B -e -V"
after_success:
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]] || [[ "${TRAVIS_BRANCH}" == release-* ]] || [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    ./.travis.scripts/mvn.sh sonar:sonar
  fi
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    ./.travis.scripts/mvn.sh -P github-site site  fi
deploy:
  provider: script
  script: "./.travis.scripts/mvn.sh -Dmaven.site.skip=true -P stage-devel-bintray
    deploy"
  skip_cleanup: true
  on:
    all_branches: true
branches:
  except:
  - gh-pages
  - master
env:
  matrix:
    secure: jQhF66P5xUGqEcQnZU1QfGDEpEMmlcz76RrHNzBAI6ojKpiUgVVqL4xFwXy853Zy1pTzgxz4ynBLjpaSZvNXBzCVnefgKqZnPKovVr4H5ltTE4jz3mOcz6PlHP3mYSdxraJqgfUX3r1CcgPUFlvuLC95yaLrBXol9Y4F76WxxuNp2pyAYe1WtYyBYupAzIUnfb/VZ2XSUdBuSAFEwPaZSGJfJaH3pQOyCjYAgPuWZmRKJ+CiFKO7cRQX3QxE2BXXvRRLMJGSdf7eIYMioM/Po9GUJQNAL79rgN7QTZkZsad75NLjwuX3XKUBL+RR852zG2URf3PBgqRXZLwhAsZ2INWcOeH0pXoi6IJCwkOgvJcEquQlNEnaD8kVjNY3IMXXkGbXikxhVotIvrRicEwq3WRvydaijRFHyohMBoB3+jPRjnU/g2VMJGTISIyQgFmlhG+/mxwdbbjRt6y22NyNKCKIQZg4VBgbDdejhXAtVzL6hufKYxnKHYmvIHZaTMpYKzVHJTwFKQHfUIECdcC0mmjY3WYA7u2XQrZjboQAYDMp8iNQ0o4UCOaUjBx25Tw1++l/2+fG8hzgNu6QbWtzQUtxetrt0lkWKHhl2LAY8FwOILtR+AacfP+oTnQ70v4CyzeZEIG2YllqdPYfzW735a8paoPsXebg3/e11xLfXak=
